baseURL: 'https://www.godliatrasop.no/'
languageCode: no-no
title: Godlia/Trasop skolers musikkorps
theme: massively
relativeURLs: 'true'

params:
  facebook: GodliaTrasop-Musikkorps-135375550518503
  instagram: godliatrasop_msk

sectionPagesMenu: main

enableGitInfo: true
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
# uglyurls: true

# menu:
#   main:
#     - identifier: _index
#       name: Godlia/Trasop
#
#     - identifier: medlemmer
#       name: For medlemmer
