CREATE TABLE `soknader` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `navn` varchar(255) DEFAULT NULL,
 `etternavn` varchar(255) DEFAULT NULL,
 `adresse` varchar(255) DEFAULT NULL,
 `postnr` char(4) DEFAULT NULL,
 `poststed` varchar(255) DEFAULT NULL,
 `tlf` char(8) DEFAULT NULL,
 `f1_navn` varchar(255) DEFAULT NULL,
 `f1_etternavn` varchar(255) DEFAULT NULL,
 `f1_adresse` varchar(255) DEFAULT NULL,
 `f1_postnr` char(4) DEFAULT NULL,
 `f1_poststed` varchar(255) DEFAULT NULL,
 `f1_tlf` char(8) DEFAULT NULL,
 `f1_epost` varchar(255) DEFAULT NULL,
 `f2_navn` varchar(255) DEFAULT NULL,
 `f2_etternavn` varchar(255) DEFAULT NULL,
 `f2_adresse` varchar(255) DEFAULT NULL,
 `f2_postnr` char(4) DEFAULT NULL,
 `f2_poststed` varchar(255) DEFAULT NULL,
 `f2_tlf` char(8) DEFAULT NULL,
 `f2_epost` varchar(255) DEFAULT NULL,
 `instr1` varchar(30) DEFAULT NULL,
 `instr2` varchar(30) DEFAULT NULL,
 `instr3` varchar(30) DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
